export enum ActionEnums {
  AUTH_IS_LOADING = "AUTH_IS_LOADING",
  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL = "SIGN_IN_FAIL",
  SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS",
  SIGN_UP_FAIL = "SIGN_UP_FAIL",
}
