name: Deploy to GCP Storage

on:
  push:
    branches:
      - main # Adjust this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust the version as needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_STORAGE_KEY }}

      - name: Upload to GCS
        run: |
          echo "${{ secrets.GCP_STORAGE_KEY }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gsutil -m cp -r dist/* gs://fixily-frontend/
